steps:
  # 1. Build the Container Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/crm-kinetic-backend-be3:$COMMIT_SHA', '.']

  # 2. Push the Image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/crm-kinetic-backend-be3:$COMMIT_SHA']

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'crm-kinetic-backend-be3'
      - '--image'
      - 'gcr.io/$PROJECT_ID/crm-kinetic-backend-be3:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/crm-kinetic-backend-be3:$COMMIT_SHA'

# --- THE FIX IS HERE ---
options:
  logging: CLOUD_LOGGING_ONLY